[package]
name = "map_visualizer"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.28.1"
rusttype = "0.9.3"
serde = {version = "1.0.204", features = ["std", "alloc", "derive", "serde_derive"]}
serde_json = "1.0.120"